export { default as Airpods } from "./airpods.jsx"
export { default as Apps } from "./apps.jsx"
export { default as Battery } from "./battery.jsx";
export { default as Border } from "./border.jsx";
export { default as Date } from "./date.jsx";
export { default as Folders } from "./folders.jsx";
export { default as Internet } from "./internet.jsx";
export { default as Sound } from "./sound.jsx";
export { default as Weather } from "./weather.jsx";
export { default as Wifi } from "./wifi.jsx";